### PR TITLE
fix ThreeUpsThenDownBot

### LINKED ISSUE #3: Fix ThreeUpsThenDownBot so it doesn't always insta-sell into fabulous losses
There's some kind of bug in ThreeUpsThenDownBot. It loses too much money too fast. There must be a bug in its implementation. Figure it out.

### PR DESCRIPTION
**Pull request by nathan-schubkegel**

### CODE REVIEW

File: ThreeUpsThenDownBot.cs [hunk 1]
```diff
@@ -68,24 +73,42 @@ public ThreeUpsThenDownBot(Decimal initialFunds)
       // can't sell if I have no coins
       if (CoinCount <= 0m) return null;
       
-      // if at any time the price drops below 5% of where I bought, then sell as a safety measure
+      // I don't know why these would be null... I just gotta ignore these scenarios for now...
```
Comment (nathan-schubkegel) [inline ThreeUpsThenDownBot.cs]: let's try to figure it out before this PR merges!

File: ThreeUpsThenDownBot.cs [hunk 2]
```diff
@@ -68,24 +73,42 @@ public ThreeUpsThenDownBot(Decimal initialFunds)
...
       
-      // if at any time the price drops below 50% of the difference 
-      // from "where I bought it" to "the max I've possibly been able to buy it"
-      // then sell as a profit-guaranteeing measure
-      if (MaxObservedPotentialSalePrice != null &&
-          (MaxObservedPotentialSalePrice.Value - LastPurchasedPerCoinPrice.Value) * 0.5m + LastPurchasedPerCoinPrice.Value > CurrentPrice.Value)
+      // if at any time the price drops below 5% of where I bought, then sell as a safety measure
+      if (CurrentPrice.Value * 0.95m > LastPurchasedPerCoinPrice.Value)
       {
+        _logger.LogInformation($"Selling because CurrentPrice ({CurrentPrice}) * 0.95m > LastPurchasedPerCoinPrice ({LastPurchasedPerCoinPrice})");
```
Comment (nathan-schubkegel) [inline ThreeUpsThenDownBot.cs]: The logger is a decent "debugging" way to reveal this info, but I would prefer a more formal way for bots to report decisions they're making that doesn't fill the console output with waste

File: ThreeUpsThenDownBot.cs [hunk 3]
```diff
@@ -68,24 +73,42 @@ public ThreeUpsThenDownBot(Decimal initialFunds)
...
+          _logger.LogInformation($"Selling because CurrentPrice ({CurrentPrice}) <= limit ({limit})");
+          return CoinCount;
+        }
+        else
+        {
+          _logger.LogInformation($"max observed price >= 0.4% up, but CurrentPrice ({CurrentPrice}) > ");
+        }
+      }
+
+      /*
```
Comment (nathan-schubkegel) [inline ThreeUpsThenDownBot.cs]: no dead code plz

File: BotProvingService.cs [hunk 4]
```diff
@@ -36,10 +37,12 @@ public interface IBotProvingService
   public class BotProvingService: IBotProvingService
   {
     private readonly ICandleService _candleService;
+    private readonly ILogger<BotProvingService> _logger;
     
-    public BotProvingService(ICandleService candleService)
+    public BotProvingService(ICandleService candleService, ILogger<BotProvingService> logger)
     {
       _candleService = candleService;
+      _logger = logger;
```
Comment (nathan-schubkegel) [inline BotProvingService.cs:45]: now this logger is unused - remove it!

Comment (nathan-schubkegel) [reply BotProvingService.cs:45]: meh - nevermind - loggers always end up getting used
